from __future__ import annotations

from .config import RetrievalConfig, VALID_RETRIEVER_MODES
from .curiosity_question_generator import (
    CURIOSITY_RESPONSE_SCHEMA,
    CURIOSITY_RESPONSE_SCHEMA_V32,
    CuriosityQuerySpec,
    CuriosityQueryResult,
    generate_curiosity_questions,
    is_explicit_parallel_question,
    is_symmetric_question,
    normalize_generated_queries,
    sanitize_generated_question,
    validate_generated_queries,
)
from .curiosity_question_prompts import build_curiosity_prompt
from .evidence_pool import (
    EvidencePoolItem,
    build_evidence_pool_items,
    merge_evidence_pool,
)
from .normal_rag import (
    AnswerContract,
    NormalRAG,
    build_evidence_context,
    build_normal_rag_prompt,
    build_rag_prompt,
    canonicalize_boolean,
    exact_match_score,
    f1_score,
    infer_answer_contract,
    normal_rag_answer,
    normal_rag_answer_from_evidence,
)
from .question_binding import (
    CONTEXT_INJECTION_ONLY_POLICY,
    ENTITY_BINDING_ONLY_POLICY,
    HYBRID_REWRITE_POLICY_PROMPT,
    MEMORY_ONLY_REWRITE_POLICY_PROMPT,
    EVIDENCE_BLIND_ADAPTER_SCHEMA,
    NO_VERIFICATION_PARSE_SCHEMA,
    RESOLUTION_ADAPTER_SCHEMA,
    RESOLUTION_REWRITE_SCHEMA,
    RewritePolicy,
    VALID_REWRITE_POLICIES,
    VerifiedResolution,
    adapt_answer_to_resolution,
    build_resolution_adapter_prompt,
    build_no_verification_parse_prompt,
    build_resolution_rewrite_prompt,
    build_verified_resolution,
    classify_rewrite_operation_type,
    classify_question_type,
    contains_answer_candidate,
    is_safe_entity_binding,
    normalize_rewrite_policy,
    render_verified_resolution,
    rewrite_question_with_resolutions,
    validate_rewrite_policy,
    validate_resolution_rewrite,
    validate_safe_transition,
)
from .novelty_detector import (
    QUESTION_SIMILARITY_THRESHOLD,
    QuestionRecord,
    build_question_record,
    check_repetition,
)
from .iterative_question_resolution import (
    ABLATION_PRESETS,
    AblationConfig,
    DATASET_RUNTIME_CONFIG,
    ResolutionState,
    VERIFICATION_ABLATION_PRESETS,
    VerificationAblationConfig,
    run_iterative_resolution,
)


def __getattr__(name: str):
    if name == "DenseRetriever":
        from .dense import DenseRetriever

        return DenseRetriever
    raise AttributeError(name)


__all__ = [
    "ABLATION_PRESETS",
    "AblationConfig",
    "VERIFICATION_ABLATION_PRESETS",
    "VerificationAblationConfig",
    "AnswerContract",
    "CURIOSITY_RESPONSE_SCHEMA",
    "CURIOSITY_RESPONSE_SCHEMA_V32",
    "CONTEXT_INJECTION_ONLY_POLICY",
    "CuriosityQuerySpec",
    "CuriosityQueryResult",
    "DATASET_RUNTIME_CONFIG",
    "EvidencePoolItem",
    "ENTITY_BINDING_ONLY_POLICY",
    "DenseRetriever",
    "NormalRAG",
    "HYBRID_REWRITE_POLICY_PROMPT",
    "MEMORY_ONLY_REWRITE_POLICY_PROMPT",
    "EVIDENCE_BLIND_ADAPTER_SCHEMA",
    "NO_VERIFICATION_PARSE_SCHEMA",
    "RESOLUTION_ADAPTER_SCHEMA",
    "RESOLUTION_REWRITE_SCHEMA",
    "RewritePolicy",
    "VALID_REWRITE_POLICIES",
    "VALID_RETRIEVER_MODES",
    "QUESTION_SIMILARITY_THRESHOLD",
    "QuestionRecord",
    "RetrievalConfig",
    "ResolutionState",
    "VerifiedResolution",
    "adapt_answer_to_resolution",
    "build_resolution_adapter_prompt",
    "build_no_verification_parse_prompt",
    "build_verified_resolution",
    "build_resolution_rewrite_prompt",
    "build_evidence_context",
    "build_curiosity_prompt",
    "build_evidence_pool_items",
    "build_normal_rag_prompt",
    "build_rag_prompt",
    "canonicalize_boolean",
    "classify_rewrite_operation_type",
    "classify_question_type",
    "contains_answer_candidate",
    "exact_match_score",
    "f1_score",
    "generate_curiosity_questions",
    "is_explicit_parallel_question",
    "is_symmetric_question",
    "normalize_generated_queries",
    "sanitize_generated_question",
    "infer_answer_contract",
    "is_safe_entity_binding",
    "merge_evidence_pool",
    "normal_rag_answer",
    "normal_rag_answer_from_evidence",
    "normalize_rewrite_policy",
    "render_verified_resolution",
    "rewrite_question_with_resolutions",
    "run_iterative_resolution",
    "validate_generated_queries",
    "validate_rewrite_policy",
    "validate_resolution_rewrite",
    "validate_safe_transition",
    "build_question_record",
    "check_repetition",
]
